"""add_users_friendship

Revision ID: 0484b946bb98
Revises: 507d2898a228
Create Date: 2025-09-25 16:11:09.610025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0484b946bb98"
down_revision: Union[str, Sequence[str], None] = "1f5941a6624c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_friendships",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("friend_id", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "ignored",
                "denied",
                "requested",
                "pending",
                "accepted",
                name="userfriendshipstate",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["friend_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "friend_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_friendships")
    # ### end Alembic commands ###
